apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hvrix10oi-go 
  janus-idp.io/tekton: hvrix10oi-go
  backstage.io/kubernetes-id: hvrix10oi-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hvrix10oi-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml