apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hvrix10oi-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hvrix10oi-go 
  name: hvrix10oi-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hvrix10oi-go 
